# Runnable without configuring the Windows build: cmake -P cmake/Architecture.cmake.
cmake_minimum_required(VERSION 3.28)
if(NOT DEFINED PROJECT_ROOT)
  get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

function(phi_module path result)
  if(path MATCHES "^(include|src)/(core|game|features|render|platform)/")
    set(module "${CMAKE_MATCH_2}")
  elseif(path MATCHES "^(include|src)/(pattern_scan|patterns)\\.")
    set(module game)
  elseif(path MATCHES "^(include|src)/overlay\\.")
    set(module overlay)
  elseif(path MATCHES "^(include|src)/(app|main)\\.")
    set(module app)
  else()
    message(FATAL_ERROR "Architecture: unclassified project file ${path}; define its module")
  endif()
  set(${result} "${module}" PARENT_SCOPE)
endfunction()

function(phi_check_sources)
  file(GLOB_RECURSE misplaced_headers RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/src/*.hpp"
    "${PROJECT_ROOT}/src/*.h" "${PROJECT_ROOT}/src/*.hh" "${PROJECT_ROOT}/src/*.hxx")
  file(GLOB_RECURSE misplaced_sources RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/include/*.cpp"
    "${PROJECT_ROOT}/include/*.cc" "${PROJECT_ROOT}/include/*.cxx" "${PROJECT_ROOT}/include/*.c")
  if(misplaced_headers OR misplaced_sources)
    message(FATAL_ERROR "Architecture: headers belong in include/ and implementations in src/: ${misplaced_headers};${misplaced_sources}")
  endif()

  file(GLOB_RECURSE files RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/include/*.hpp"
    "${PROJECT_ROOT}/include/*.h" "${PROJECT_ROOT}/src/*.cpp")
  foreach(path IN LISTS files)
    phi_module("${path}" module)
    file(READ "${PROJECT_ROOT}/${path}" content)
    # Ignore ordinary comments before examining literal includes.
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" content "${content}")
    string(REGEX REPLACE "//[^\n]*" "" content "${content}")
    string(REGEX MATCHALL "(^|\n)[ \t]*#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" includes "${content}")
    foreach(line IN LISTS includes)
      string(REGEX REPLACE ".*include[ \t]*[<\"]([^>\"]+)[>\"].*" "\\1" header "${line}")
      get_filename_component(parent "${PROJECT_ROOT}/${path}" DIRECTORY)
      if(EXISTS "${parent}/${header}")
        get_filename_component(resolved "${parent}/${header}" REALPATH)
      elseif(EXISTS "${PROJECT_ROOT}/include/${header}")
        get_filename_component(resolved "${PROJECT_ROOT}/include/${header}" REALPATH)
      else()
        # Core is portable. Features may only use standard headers externally.
        if(module MATCHES "^(core|features)$" AND header MATCHES "[/\\\\.]|^(windows|Windows|d3d.*|dxgi.*|safetyhook|imgui)$")
          message(FATAL_ERROR "Architecture: ${path} cannot include external platform header ${header}")
        endif()
        if(module MATCHES "^(game|platform)$" AND header MATCHES "^(imgui|backends/|d3d|dxgi)")
          message(FATAL_ERROR "Architecture: ${path} cannot include graphics header ${header}")
        endif()
        if(module STREQUAL platform AND header MATCHES "^safetyhook")
          message(FATAL_ERROR "Architecture: ${path} cannot include hook header ${header}")
        endif()
        continue()
      endif()
      file(RELATIVE_PATH dependency "${PROJECT_ROOT}" "${resolved}")
      if(NOT dependency MATCHES "^include/")
        message(FATAL_ERROR "Architecture: ${path} includes ${dependency} outside include/")
      endif()
      phi_module("${dependency}" dependency_module)
      set(allowed FALSE)
      if(module STREQUAL dependency_module OR module STREQUAL app)
        set(allowed TRUE)
      elseif(module STREQUAL game AND dependency_module STREQUAL core)
        set(allowed TRUE)
      elseif(module STREQUAL features AND dependency MATCHES "^include/(game/(treasure_observer|minimap_observer|menu_observer)|render/hud_state)\\.hpp$")
        set(allowed TRUE)
      elseif(module STREQUAL overlay AND dependency_module STREQUAL render)
        set(allowed TRUE)
      endif()
      if(NOT allowed)
        message(FATAL_ERROR "Architecture: forbidden include ${path} -> ${dependency}")
      endif()
    endforeach()
  endforeach()
endfunction()

# Inspect actual CMake target properties rather than parsing CMakeLists.txt text.
function(phi_check_target target)
  set(allowed ${ARGN})
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(dependencies "${target}" "${property}")
    if(NOT dependencies)
      continue()
    endif()
    foreach(dependency IN LISTS dependencies)
      string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" dependency "${dependency}")
      if(NOT dependency IN_LIST allowed)
        message(FATAL_ERROR "Architecture: forbidden target dependency ${target} -> ${dependency}")
      endif()
    endforeach()
  endforeach()
endfunction()

phi_check_sources()
message(STATUS "Architecture source checks passed")
