cmake_minimum_required(VERSION 3.28)
get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED TEST_ROOT)
  set(TEST_ROOT "${REPO_ROOT}/build/architecture-tests")
endif()

function(check_case name relative_path content expected)
  set(root "${TEST_ROOT}/${name}")
  file(MAKE_DIRECTORY "${root}")
  file(WRITE "${root}/${relative_path}" "${content}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPROJECT_ROOT=${root}"
    -P "${REPO_ROOT}/cmake/Architecture.cmake" RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected STREQUAL "PASS")
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "${name} unexpectedly failed: ${output}${error}")
    endif()
  elseif(result EQUAL 0 OR NOT "${error}" MATCHES "${expected}")
    message(FATAL_ERROR "${name} did not reject the intended violation: ${output}${error}")
  endif()
endfunction()

check_case(header_in_src src/render/bad.hpp "#pragma once\n" "headers belong in include")
check_case(source_in_include include/render/bad.cpp "int value;\n" "headers belong in include")
file(WRITE "${TEST_ROOT}/core_to_render/include/render/hud_state.hpp" "#pragma once\n")
check_case(core_to_render include/core/bad.hpp "#include <render/hud_state.hpp>\n" "forbidden include")
check_case(features_to_windows include/features/bad.hpp "#include <windows.h>\n" "external platform")
check_case(portable_core include/core/good.hpp "#include <vector>\n// #include <windows.h>\n" "PASS")
file(WRITE "${TEST_ROOT}/game_to_core/include/core/signal.hpp" "#pragma once\n")
check_case(game_to_core include/game/good.hpp "#include \"core/signal.hpp\"\n" "PASS")
file(WRITE "${TEST_ROOT}/render_to_game/include/game/treasure_observer.hpp" "#pragma once\n")
check_case(render_to_game include/render/bad.hpp "#include \"game/treasure_observer.hpp\"\n" "forbidden include")
file(WRITE "${TEST_ROOT}/feature_to_hud/include/render/hud_state.hpp" "#pragma once\n")
check_case(feature_to_hud include/features/good.hpp "#include \"render/hud_state.hpp\"\n" "PASS")

set(root "${TEST_ROOT}/target_dependency")
file(WRITE "${root}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.28)\nproject(ArchitectureFixture NONE)\nset(PROJECT_ROOT \"${root}\")\ninclude(\"${REPO_ROOT}/cmake/Architecture.cmake\")\nadd_library(game_observers INTERFACE)\ntarget_link_libraries(game_observers INTERFACE imgui_static)\nphi_check_target(game_observers safetyhook)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${error}" MATCHES "forbidden target dependency")
  message(FATAL_ERROR "Forbidden target dependency was not detected: ${output}${error}")
endif()

file(WRITE "${TEST_ROOT}/feature_to_minimap/include/game/minimap_observer.hpp" "#pragma once\n")
check_case(feature_to_minimap include/features/good.hpp "#include \"game/minimap_observer.hpp\"\n" "PASS")
file(WRITE "${TEST_ROOT}/render_to_minimap/include/game/minimap_observer.hpp" "#pragma once\n")
check_case(render_to_minimap include/render/bad.hpp "#include \"game/minimap_observer.hpp\"\n" "forbidden include")

message(STATUS "Architecture checker regression tests passed")

foreach(module render overlay platform)
  set(case "${module}_to_log_contract")
  file(WRITE "${TEST_ROOT}/${case}/include/core/log.hpp" "#pragma once\n")
  if(module STREQUAL overlay)
    set(path include/overlay.hpp)
  else()
    set(path "include/${module}/good.hpp")
  endif()
  check_case("${case}" "${path}" "#include \"core/log.hpp\"\n" "PASS")
endforeach()
file(WRITE "${TEST_ROOT}/render_to_logger/include/platform/logger.hpp" "#pragma once\n")
check_case(render_to_logger include/render/bad.hpp "#include \"platform/logger.hpp\"\n" "forbidden include")
file(WRITE "${TEST_ROOT}/game_to_logger/include/platform/logger.hpp" "#pragma once\n")
check_case(game_to_logger include/game/bad.hpp "#include \"platform/logger.hpp\"\n" "forbidden include")
