cmake_minimum_required(VERSION 3.28)
foreach(name PirateHatHUD.asi PirateHatHUD.ini modinfo.json LICENSE THIRD_PARTY_NOTICES.md
    LICENSE-SafetyHook.txt LICENSE-DearImGui.txt LICENSE-Zydis.txt)
  if(NOT EXISTS "${STAGE_DIR}/${name}")
    message(FATAL_ERROR "Missing distribution file: ${name}")
  endif()
endforeach()
foreach(name config.ini icon.png)
  if(EXISTS "${STAGE_DIR}/${name}")
    message(FATAL_ERROR "Legacy distribution file remains: ${name}")
  endif()
endforeach()
file(READ "${STAGE_DIR}/modinfo.json" metadata)
string(JSON version GET "${metadata}" version)
if(NOT version STREQUAL EXPECTED_VERSION)
  message(FATAL_ERROR "Package metadata version ${version} differs from ${EXPECTED_VERSION}")
endif()
file(READ "${STAGE_DIR}/PirateHatHUD.ini" config)
if(NOT config MATCHES "\\[indicator\\]" OR NOT config MATCHES "\\[hotkeys\\]")
  message(FATAL_ERROR "Missing runtime configuration sections")
endif()
